### ISSUE TITLE
ff-analogy utility

### ISSUE THREAD

**Issue by danieldk** [finalfusion/finalfusion-utils#1]
I just realized that we do not have an `ff-analogy` utility. This should lines from the standard input consisting of three words separated by a space. If the words are *A B C*, then it should return words that qualify as *D* in *A is to B as C is to D*.

Analogy queries are already supported by the `finalfusion` crate. So, this utility would be largely a copy of `ff-similar`, but reading three words rather than one word and using the `analogy` method.

@NianhengWu: maybe this is something that you could do besides the finalfrontier experiments? Seems like little work for a lot of gratification ;). You can get embeddings to test with at:

https://finalfusion.github.io/pretrained

**Comment by NianhengWu** [comment]
Sure! On it :) Thanks!

**Comment by danieldk** [comment]
Added in #6
