### ISSUE TITLE
Handling missing input stream/file

### ISSUE THREAD

**Issue by sebpuetz** [finalfusion/finalfusion-utils#33]
We have a number of tools that just quietly do nothing if we forget to pass an input. Maybe printing a status message to stderr stating something like `Reading input from stdin` or `Reading input from path/to/file` would allow users to catch that.

What's your opinion?

**Comment by danieldk** [comment]
Most other UNIX utilities don't do that, so I think we shouldn't do that either.

**Comment by sebpuetz** [comment]
#36 adds some kind of feedback, that was also the tool which had me waiting for 10 minutes before I realized my machine was idling ;)
