### ISSUE TITLE
Do not silently fail if embeddings cannot be computed/looked up in ff-{analogy,similar}

### ISSUE THREAD

**Issue by danieldk** [finalfusion/finalfusion-utils#8]
Proposed solution: change `analogy` to return a `Result<..., [bool; 3]>`, then print failed words.

**Comment by NianhengWu** [comment]
Now that `analogy_masked` returns a Result, I think maybe `similarity_by` better do the same? And also, corresponding need to be changed to.

**Comment by danieldk** [comment]
> Now that `analogy_masked` returns a Result, I think maybe `similarity_by` better do the same?

Could you explain why? The similarity functions only look up one word, so all that needs to be known can be communicated with `Option`.

**Comment by sebpuetz** [comment]
I think the only case for `similarity_by` to fail is the degenerate case of an embedding space with a single vector.

> (I think `Result::Err` is a bit of a misnomer in this case, Haskell's Either is more logical.)

Usage of `Result::Err` to communicate this kind of info is also done in the standard library with `binary_search`, iirc, `Err` is returned with the insertion index if an item was not found. I guess some custom enum would also better fit the semantics there...

**Comment by danieldk** [comment]
Yes, the standard library uses `Err` as well. But for me, there is a difference between:

* Errors
* Partial functions (in the case of partial functions, it may still be useful to distinguish different types of outside the input domain).
* Functions that can return two different types of results (e.g. `binary_search`).

The argument against custom types is that you cannot leverage all standard functionality that is available for `Result`. But had they named `Result` something like `Either`, it would be more neutral.

But this is what we have to live with ;).

**Comment by NianhengWu** [comment]
> > Now that `analogy_masked` returns a Result, I think maybe `similarity_by` better do the same?
> 
> Could you explain why? The similarity functions only look up one word, so all that needs to be known can be communicated with `Option` this is also in line with Rust collections.
> 
> (I think `Result::Err` is a bit of a misnomer in this case, Haskell's `Either` is more logical.)

I'm just thinking it would be better if it does not fail silently,
 
Yeah `Err` is probably not a good idea.

But printing something to tell people that it fails maybe still necessary? Because now in ff-similar it just continues if it fails on some words.

**Comment by danieldk** [comment]
> I'm just thinking it would be better if it does not fail silently,

It returns `Option`, so the method does not fail silently. The `ff-similar` utility might. The goal was to change `ff-analogy` and `ff-similar` next. But I am holding off a bit, since there is a large other change in the pipeline (better error types).
